name: Run tests
on: [push]
jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        # TODO: test with py3.4 to ensure this runs on micropython
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt install -y mypy black flake8
      - name: Run unit tests 
        run: python3 -m unittest
